name: Plugin test
on:
  pull_request:

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  with-krew:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup cluster
        uses: ./.github/workflows/cluster-setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install krew
        run: tests/github-action-helper.sh install_krew

      - name: Test plugin with ceph commands
        run: |
          export PATH="${PATH}:${HOME}/.krew/bin"
          # run ceph commands with the krew plugin
          kubectl rook-ceph ceph status
          kubectl rook-ceph ceph status -f json
          kubectl rook-ceph ceph status --format json-pretty
          kubectl rook-ceph ceph mon stat

  # This test is required to test latest changes or the changes that not present
  # with current version of rook-ceph krew plugin
  with-pr-changes-in-default-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup cluster
        uses: ./.github/workflows/cluster-setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install script
        run: sudo install kubectl-rook-ceph.sh /usr/local/bin/kubectl-rook_ceph

      - name: Test Plugin
        run: |
          kubectl rook_ceph ceph status
          kubectl rook_ceph ceph status -f json
          kubectl rook_ceph ceph status --format json-pretty
          POD=$(kubectl -n rook-ceph get pod -l app=rook-ceph-operator -o jsonpath="{.items[0].metadata.name}")
          kubectl rook_ceph operator restart

          # let's wait for operator pod to be restart
          kubectl -n rook-ceph wait --for=delete pod/$POD --timeout=100s
          tests/github-action-helper.sh wait_for_operator_pod_to_be_ready_state_default
          kubectl rook_ceph operator set ROOK_LOG_LEVEL DEBUG
          kubectl rook_ceph --context=$(kubectl config current-context) mons
          kubectl rook_ceph rook version
          kubectl rook_ceph rook status
          kubectl rook_ceph rook status all
          kubectl rook_ceph rook status cephobjectstores
          # to allow time for reconcile, sleep before listing the pools
          sleep 10
          kubectl rook_ceph rbd ls replicapool

          # for testing start-debug and stop-debug deployment
          # mons
          kubectl rook_ceph debug start rook-ceph-mon-a
          sleep 5
          kubectl rook_ceph debug stop rook-ceph-mon-a
          # osd
          kubectl rook_ceph debug start rook-ceph-osd-0
          sleep 5
          kubectl rook_ceph debug stop rook-ceph-osd-0

          # sleep again so OSD can start
          sleep 5

          # for testing osd purge scale the osd deplyment
          kubectl --namespace rook-ceph scale deploy/rook-ceph-osd-0 --replicas=0
          # we need to sleep so the osd will be marked down before purging the osd
          sleep 5
          kubectl rook_ceph rook purge-osd 0 --force
          kubectl rook_ceph health

      - name: setup tmate session for debugging when event is PR
        if: failure() && github.event_name == 'pull_request'
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
